t = turtle.Turtle()
t.fillcolor('green')
t.begin_fill()
for i in range(4):
  t.forward(150)
  t.right(60)
t.end_fill()
t = turtle.Turtle()
t.fillcolor('orange')
t.begin_fill()
for i in range(5):
  t.forward(150)
  t.right(144)
t.end_fill()
t = turtle.Turtle()
t.fillcolor('orange')
t.begin_fill()
t.circle(100)
t.end_fill()
